#ifndef RESOURCE2_H_INCLUDED
#define RESOURCE2_H_INCLUDED

#define IDC_STATUSBAR 790
#define IDM_CONTEXTSAVESONG 789
#define IDM_CONTEXTCHECKSELECTED 791
#define IDM_CONTEXTUNCHECKSELECTED 792

#endif // RESOURCE2_H_INCLUDED
